[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && pip install playwright && playwright install chromium"

[deploy]
startCommand = "gunicorn webhook_server:app --bind 0.0.0.0:$PORT"

[deploy.env]
PORT = "3003" 